networks:
  web:
  
volumes:
  storage: {}
  dbfile: {}

services:
  app:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    env_file: backend/.env.prod
    volumes:
      - storage:/app/storage
      - dbfile:/app/database
      - ./backend/.env.prod:/app/.env:ro
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(extension_loaded(\"pdo_sqlite\")?0:1);'"]
      interval: 30s
      timeout: 5s
      retries: 3

  ########################  Queue Worker  ########################
  queue:
    image: laravel_app
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - storage:/app/storage
      - dbfile:/app/database
    networks: [web]

  ########################  React Frontend  ########################
  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    container_name: react_front
    restart: unless-stopped
    networks: [web]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]  # ← استفاده از curl بجای wget
      interval: 30s
      timeout: 3s
      retries: 3
