services:
  # database:
  #   image: docker.arvancloud.ir/mysql:8.0
  #   container_name: database
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - database-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MEHR_DATABASE_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MEHR_DATABASE_DB_NAME}
  #   networks:
  #     - mehr-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "mysqladmin",
  #         "ping",
  #         "-h",
  #         "localhost",
  #         "-u",
  #         "root",
  #         "-p${MEHR_DATABASE_ROOT_PASSWORD}",
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  dbmanager:
    image: docker.arvancloud.ir/phpmyadmin
    container_name: dbmanager
    # depends_on:
    #   database:
    #     condition: service_healthy
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"
    networks:
      - mehr-network
    restart: unless-stopped

volumes:
  database-data:

networks:
  mehr-network:
    driver: bridge
