# فایل اصلی – مناسب Production
# نگارش بر پایهٔ Docker Compose v2 (کلید version حذف شده است)

########################
# شبکه و ولوم مشترک
########################
networks:
  web:

volumes:
  storage:   # لاگ و فایل‌های کاربر
  dbfile:    # دیتابیس SQLite

########################
# سرویس‌ها
########################
services:

  ########################  Laravel (PHP‑FPM)  ########################
  app:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile   # ← همان Dockerfile چندمرحله‌ای
    container_name: laravel_app
    restart: unless-stopped
    env_file: backend/.env.prod               # .env مخصوص Production
    volumes:
      - storage:/app/storage                  # استوریج پایدار
      - dbfile:/app/database                  # فایل SQLite
      - ./backend/.env.prod:/app/.env:ro      # فقط خواندنی
    networks: [web]
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(extension_loaded(\"pdo_sqlite\")?0:1);'"]
      interval: 30s
      timeout: 5s
      retries: 3

  ########################  Queue Worker  ########################
  queue:
    image: laravel_app                        # همان ایمیج ساخته‌شده
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - storage:/app/storage
      - dbfile:/app/database
    networks: [web]

  ########################  React Frontend  ########################
  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    container_name: react_front
    restart: unless-stopped
    networks: [web]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
